# Phase 1 Configuration (Inherits from base.yaml)
defaults:
  - base

loss:
  ctc_weight: 0.5
  ce_weight: 0.5

logging:
  checkpoint_dir: "/mnt/checkpoints/phase1"

data:
  train_manifest: "/mnt/vicocktail_features/avvn-test_snr_0_interferer_1-000000_manifest.jsonl"
  val_manifest: "/mnt/vicocktail_features/avvn-test_snr_0_interferer_1-000000_manifest.jsonl"
  data_root: "/mnt/vicocktail_features/avvn-test_snr_0_interferer_1-000000"
