import sys
import os
import torch
import torch.optim as optim
from torch.utils.data import DataLoader
from tqdm import tqdm
from pathlib import Path

# Add project root
sys.path.append(os.getcwd())

from src.data.loader import build_dataloader
from src.data.tokenizers.whisper import WhisperTokenizer
from src.models.fusion.aurora_xt_model import create_model

def main():
    # --- Config ---
    config = {
        # Data
        "data_root": "test_data_dummy", # Change to real path
        "train_manifest": "grid_manifest.jsonl", # Generated by preprocessor
        "val_manifest": "grid_manifest.jsonl",   # Use same for quick test
        "batch_size": 4,
        "num_workers": 0,
        "use_precomputed_features": True, # PHASE 1 KEY
        
        # Model
        "audio_dim": 768,
        "visual_dim": 512,
        "d_model": 256,
        "num_encoder_layers": 4,
        "num_decoder_layers": 2,
        "vocab_size": 0, # Will be set from tokenizer
        
        # Training
        "epochs": 2,
        "lr": 1e-4,
        "device": "cuda" if torch.cuda.is_available() else "cpu"
    }
    
    print(f"🚀 Starting Phase 1 Training on {config['device']}")
    
    # 1. Tokenizer
    tokenizer = WhisperTokenizer(language="en")
    # Whisper has special tokens up to 51865. Use safe buffer.
    config['vocab_size'] = 51866 
    print(f"   Vocab Size: {config['vocab_size']}")
    
    # 2. DataLoaders
    # Ensure manifests exist (mock if needed for this script test)
    if not os.path.exists(config['train_manifest']):
        print(f"⚠️  Manifest {config['train_manifest']} not found. Run preprocessor first!")
        return

    train_loader = build_dataloader(config, tokenizer, mode='train')
    
    # 3. Model
    model = create_model(config).to(config['device'])
    optimizer = optim.AdamW(model.parameters(), lr=config['lr'])
    ctc_loss_fn = torch.nn.CTCLoss(blank=tokenizer.pad_token_id, zero_infinity=True)
    
    # 4. Loop
    for epoch in range(config['epochs']):
        model.train()
        total_loss = 0
        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{config['epochs']}")
        
        for batch in pbar:
            audio = batch['audio'].to(config['device'])
            visual = batch['visual'].to(config['device'])
            targets = batch['target'].to(config['device']) # [B, L]
            
            # Forward
            # Note: Targets for AR decoder should exclude -100 if handled inside?
            # AuroraXT decoder handles target embedding. We need to handle padding logic carefully.
            # Ideally replace -100 with pad_token_id for embedding lookups
            targets_inp = targets.clone()
            targets_inp[targets_inp == -100] = tokenizer.pad_token_id
            
            outputs = model(audio, visual, targets_inp)
            
            # Loss Calculation (Simple CTC for now)
            ctc_logits = outputs['ctc_logits'] # [B, T, V]
            
            # CTC Loss expects: Logits [T, B, V], Targets [B, L], InputLens [B], TargetLens [B]
            log_probs = ctc_logits.log_softmax(dim=2).permute(1, 0, 2) # [T, B, V]
            
            input_lengths = torch.full(size=(audio.size(0),), fill_value=ctc_logits.size(1), dtype=torch.long)
            target_lengths = torch.sum(targets != -100, dim=1)
            
            loss = ctc_loss_fn(log_probs, targets, input_lengths, target_lengths)
            
            # Backward
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
            total_loss += loss.item()
            pbar.set_postfix({'loss': loss.item()})
            
        print(f"Epoch {epoch+1} Avg Loss: {total_loss / len(train_loader):.4f}")
        
    print("✅ Training Loop Finished Successfully")

if __name__ == "__main__":
    main()
